trigger:
- master

pool: MyAgentPool

steps:
- script: |
    echo "Setting JAVA_HOME"
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  displayName: 'Set JAVA_HOME'

- task: Maven@3
  inputs:
    mavenPomFile: 'productcatalogue/pom.xml'
    mavenOptions: '-Xmx3072m'
    # javaHomeOption et javaHome sont supprimés
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

