trigger:
- master

pool: MyAgentPool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'productcatalogue/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    javaHome: '/usr/lib/jvm/java-8-openjdk-amd64' # Chemin vers Java 8
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'


