trigger:
- master

variables:
  - name: JAVA_HOME_11_X64
    value: /usr/lib/jvm/java-11-openjdk-amd64

stages:
- stage: Build
  jobs:
  - job: MavenBuild
    displayName: Compilation maven
    continueOnError: false
    pool:
      name: MyAgentPool
    steps:
    - task: Maven@3
      displayName: 'Build shopfront'
      inputs:
        mavenPomFile: 'shopfront/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: Maven@3
      displayName: 'Build productcatalogue'
      inputs:
        mavenPomFile: 'productcatalogue/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: Maven@3
      displayName: 'Build stockmanager'
      inputs:
        mavenPomFile: 'stockmanager/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
