trigger:
- master

pool:
  name: MyAgentPool

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - checkout: self
  - script: echo "Début de la construction du projet..."
    displayName: 'Étape de démarrage'

  - task: Maven@3
    displayName: 'Build avec Maven'
    inputs:
      mavenPomFile: 'pom.xml' # Mettez à jour ce chemin vers le fichier POM de votre projet
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      goals: 'package'

  - script: echo "Construction terminée."
    displayName: 'Étape de fin'

