apiVersion: v1
kind: PersistentVolume
metadata:
  name: product-catalogue-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/product-catalogue
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-catalogue-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: product-catalogue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      containers:
      - name: product-catalogue
        image: product-catalogue:latest
        volumeMounts:
        - name: product-catalogue-volume
          mountPath: /data/product-catalogue
      volumes:
      - name: product-catalogue-volume
        persistentVolumeClaim:
          claimName: product-catalogue-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue-service
spec:
  selector:
    app: productcatalogue  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


